server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # If we have customized Gateway configuration( example : ApiGatewayConfiguration.java class ), these are not necessarry

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka