server:
  port: 8765
spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://localhost:8888/" #for communication with spring cloud config server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # connect with my discovery server which is Eureka Server
          lower-case-service-id: true # If we have customized Gateway configuration( example : ApiGatewayConfiguration.java class ), these are not necessarry
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true # to show information about the service

info:
  app:
    name: "api-gateway"
    description: "Api Gateway for logging, security, load balancing"
    version: "0.0.1"

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
