server:
  port: 8765
spring:
  application:
    name: api-gateway
#  profiles:
#    active: "prod"
#  config:
#    import: "configserver:http://localhost:8888/" #for communication with spring cloud config server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true # If we have customized Gateway configuration( example : ApiGatewayConfiguration.java class ), these are not necessarry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
