version: '3.7'

services:
  config-server:
    image: caksuna/config-server:0.0.1
    ports:
      - "8888:8888"
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - advanced-microservice

  naming-server:
    image: caksuna/advanced-microservice-naming-server:0.0.1
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      - advanced-microservice
    environment:
      SPRING_CONFIG_IMPORT: "http://config-server:8888/"
      SPRING_APPLICATION_NAME: "naming-server"
      SPRING_PROFILES_ACTIVE: default

  zipkin-server:
    image: openzipkin/zipkin:2.23
    ports:
      - "9411:9411"
    networks:
      - advanced-microservice

  api-gateway:
    image: caksuna/advanced-microservice-api-gateway:0.0.1
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
      - config-server
    networks:
      - advanced-microservice
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_APPLICATION_NAME: "api-gateway"
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "http://config-server:8888/"

  currency-exchange:
    image: caksuna/advanced-microservice-currency-exchange-service:0.0.1
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
      - config-server
    networks:
      - advanced-microservice
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_APPLICATION_NAME: "currency-exchange"
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "http://config-server:8888/"

  currency-conversion:
    image: caksuna/advanced-microservice-currency-conversion-service:0.0.1
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
      - config-server
    networks:
      - advanced-microservice
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING_APPLICATION_NAME: "currency-conversion"
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: "http://config-server:8888/"

networks:
  advanced-microservice:
