version: '3.7'

services:
  naming-server:
    image: in28min/mmv2-naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - currency-network

  # docker run -p 9411:9411 -d(optional) -m 300mb openzipkin/zipkin:2.23
  zipkin-server:
    image: openzipkin/zipkin:2.23
#    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network

  api-gateway:
    image: in28min/mmv2-api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    depends_on:
      - naming-server
    networks:
      - currency-network
      - config-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  currency-exchange:
    image: in28min/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
#    mem_limit: 700m
    ports:
      - "8000:8000"
    depends_on:
      - naming-server
    networks:
      - currency-network
      - config-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  currency-conversion:
    image: in28min/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
#    mem_limit: 700m
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
      - config-server
    networks:
      - currency-network
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  config-server:
#    image: ... -- TODO IMAGE OLUSTUR
    ports:
      - "8888:8888"
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - currency-network
#    extends: todo : bu dosyalar hazırlanacak
#      file: common-config.yml
#      service: microservice-base-config

networks:
  currency-network:
