server:
  port: 8080

spring:
  application:
    name: currency-conversion
  config:
    import: "configserver:http://localhost:8888/" #for communication with spring cloud config server
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "currency-conversion"
    description: "Currency Conversion for conversion"
    version: "0.0.1"
