server:
  port: 8080

spring:
  application:
    name: currency-conversion
  config:
    import: "configserver:http://localhost:8888/" #for communication with spring cloud config server
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
