server:
  port: 8761

spring:
  application:
    name: naming-server
  profiles:
    active: "prod"
  config:
    import: "configserver:http://localhost:8888/" #for communication with spring cloud config server
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
