server:
  port: 8000
spring:
  application:
    name: currency-exchange
  profiles:
    active: "prod"
  config:
    import: "configserver:http://localhost:8888/" #for communication with spring cloud config server
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
resilience4j:
#  retry:
#    instances:
#      currencyExchangeService:
#        maxAttempts: 5
#        waitDuration: 1s
#        enableExponentialBackOff: true
  circuitbreaker:
    instances:
      currencyExchangeService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
