spring:
  server:
    port: 8000
  jpa:
    defer-datasource:
      initialization: true
    show-sql: true
    hibernate:
      ddl-auto: true
    datasource:
      url:jdbc: h2:mem:testdb
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

      spring.datasource.username=username
      spring.datasource.password=password